AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  mockdopa:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'th.generali.mockdopa.lambda.Handler::handleRequest'
      Runtime: java8.al2
      CodeUri: './target/classes'
      Description: ''
      MemorySize: 512
      Timeout: 15
      Role: 'arn:aws:iam::593947464958:role/service-role/mock-dopa-role-2hoatopn'
      Events:
        mockdopa:
          Type: Api 
          Properties:
            Path: /dopa/check
            Method: post
